- name:  Installing Redis
  hosts: redis
  become: yes
  tasks:
  - name: Enable Redis 7 version
    ansible.builtin.command: dnf module enable redis:7 -y
  
  - name: Install Redis
    ansible.builtin.dnf:
      name: redis
      state: present
  
  - name: Allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disabling protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

  - name: Enable and start service
    ansible.builtin.systemd_service:
      name: redis
      state: started
      enabled: true



