- name: crate EC2 instance and update R53 records
  hosts: local
  connection: local
  become: yes
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-0238a21d11979a649"
    zone_id: "Z04304691CJEXLOI5ZISX"
    action: "create"
    env: "dev"
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create EC2 instance
    amazon.aws.ec2_instance:
      name: {{instance}}-{{env}}
      instance_type: t3.micro
      image_id: {{ami_id}}
      security_group: {{sg_id}}
      state: present
      tags:
      - Name: "{{instance}}-{{env}}}"
        Project: Roboshop
        Environment: {{env}}
        Component: {{item}}
      loops: {{instances}} 
      register: output

    - name: print the response
      ansible.builtin.debug:
        msg: "{{output}}"
      
    # - name: R53 record update
    #   amazon.aws.route53:
    #     hosted_zone_id: {{zone_id}}
    #     record: 
    #     type: A
    #     value: {{output:instance[0]}}
    #     ttl: 300
    #     state: present


