- name: crate EC2 instance and update R53 records
  hosts: local
  connection: local
  become: yes
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-0238a21d11979a649"
    zone_id: "Z04304691CJEXLOI5ZISX"
    domain_name: "rajeshirrinki.online"
    action: "create"
    env: "dev"
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create EC2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}-{{ env }}"
      instance_type: "t3.micro"
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
      tags:
        Name: "{{ item }}-{{ env }}}"
        Project: Roboshop
        Env: "{{ env }}"
        Component: "{{ item }}"
    loop: "{{ instances }}" 
    register: ec2_output
    when: action == "create"

  - name: print the response
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
      
  - name: R53 record update
    amazon.aws.route53:
      hosted_zone_id: "{{ zone_id }}"
      zone: "{{ domain_name }}"
      record: "{{item.item}}-{{env}}-{{domain_name}}"
      type: A
      value: "{{ item.instances[0].rivate_ip_address }}"
      ttl: 300
      state: present
      overwrite: true
    loop: "{{ec2_output.results}}"
    when: action == "create" and "item.item" != "frontend"
    


